//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuanApiService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApiDatabaseConnection : DbContext
    {
        public ApiDatabaseConnection()
            : base("name=ApiDatabaseConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Suscripcione> Suscripciones { get; set; }
        public virtual DbSet<SuscripcionServicio> SuscripcionServicios { get; set; }
        public virtual DbSet<Suscriptor> Suscriptors { get; set; }
    }
}
