//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuanApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscripcione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suscripcione()
        {
            this.SuscripcionServicios = new HashSet<SuscripcionServicio>();
        }
    
        public int SuscripcionId { get; set; }
        public Nullable<int> ServicioId { get; set; }
        public int ClienteId { get; set; }
        public int SuscriptorId { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Suscriptor Suscriptor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuscripcionServicio> SuscripcionServicios { get; set; }
    }
}
