//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuanApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuscripcionServicio
    {
        public int SuscServiciosId { get; set; }
        public int ServicioId { get; set; }
        public int SuscripcionId { get; set; }
    
        public virtual Servicio Servicio { get; set; }
        public virtual Suscripcione Suscripcione { get; set; }
    }
}
