//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServPlan
    {
        public int ServPlanID { get; set; }
        public int ServicioID { get; set; }
        public int PlanID { get; set; }
    
        public virtual Plane Plane { get; set; }
        public virtual Plane Plane1 { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
