//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSuscriptionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.ClienteSuscripcions = new HashSet<ClienteSuscripcion>();
        }
    
        public int ClientID { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public System.DateTime Fecha_de_nacimiento { get; set; }
        public string Numero_Telefonico { get; set; }
        public string e_mail { get; set; }
        public string Metodo_de_Pago { get; set; }
        public Nullable<int> NumeroTarjeta { get; set; }
        public Nullable<int> CVC_o_CVV { get; set; }
        public Nullable<System.DateTime> Fecha_de_expiracion { get; set; }
        public Nullable<int> ImagenID { get; set; }
        public Nullable<int> IDPedro { get; set; }
        public Nullable<int> IDErick { get; set; }
    
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteSuscripcion> ClienteSuscripcions { get; set; }
    }
}
