//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace MVCSuscriptionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilUsuario
    {
        public int perfilUserId { get; set; }
        public int perfilId { get; set; }
        public string userId { get; set; }

        [JsonIgnore]
        public virtual Perfile Perfile { get; set; }
    }
}
