//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSuscriptionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscripcion()
        {
            this.ClienteSuscripcions = new HashSet<ClienteSuscripcion>();
        }
    
        public int SubscripcionID { get; set; }
        public int PlanID { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteSuscripcion> ClienteSuscripcions { get; set; }
        public virtual Image Image { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
